### ISSUE TITLE
unable to evaluate results on adversarial examples (apart from mnist used)

### ISSUE THREAD

**Issue by rohit789123** [tensorflow/cleverhans#1048]
**Describe the bug**
For new data normal evaluation(non adversarial data) is working fine, but for adversarial examples (being generated out of new data) , error is getting thrown when evaluation is being performed on those adversarial examples.

I have performed evaluation on adversarial examples generated using MNIST data and that seems to be working fine. 

I made sure that the dimensions and the data type of my new data is similar to that of MNIST.

Apart from that, evaluation on new data (original examples) is running fine.  
 
**To Reproduce**
  # evaluation script

    def do_eval(preds, x_set, y_set, report_key, is_adv=None):
      acc = model_eval(sess, x, y, preds, x_set, y_set, args=eval_params)
      print("printing the value of accuracy",acc)
    
      setattr(report, report_key, acc)
      if is_adv is None:
        report_text = None
      elif is_adv:
        report_text = 'adversarial'
      else:
        report_text = 'legitimate'
      if report_text:
        print('Test accuracy on %s examples: %0.4f' % (report_text, acc))

    if clean_train:
      model = ModelBasicCNN('model1', nb_classes, nb_filters)
      preds = model.get_logits(x)
      loss = CrossEntropy(model, smoothing=label_smoothing)

      # generation of adversarial examples
      fgsm = FastGradientMethod(model, sess=sess)
      adv_x = fgsm.generate(x, **fgsm_params)
      preds_adv = model.get_logits(adv_x)

      # evaluation on normal and adversarial examples
      def evaluate():
        do_eval(preds, x_test, y_test, 'clean_train_clean_eval', False)
        do_eval(preds_adv, x_test, y_test, 'train_clean_train_adv_eval',True)

# ERROR
Traceback (most recent call last):
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x <= y did not hold element-wise:x (Placeholder:0) = ] [[[[70][90][90]]]...] [y (Cast_3/x:0) = ] [1]
	 [[Node: assert_less_equal_1/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_FLOAT, DT_STRING, DT_FLOAT], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](assert_less_equal_1/Assert/AssertGuard/Assert/Switch, assert_less_equal_1/Assert/AssertGuard/Assert/data_0, assert_less_equal_1/Assert/AssertGuard/Assert/data_1, assert_less_equal_1/Assert/AssertGuard/Assert/Switch_1, assert_less_equal_1/Assert/AssertGuard/Assert/data_3, assert_less_equal_1/Assert/AssertGuard/Assert/Switch_2/_95)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mnist_tutorial_tf_new_tsr.py", line 321, in <module>
    tf.app.run()
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "mnist_tutorial_tf_new_tsr.py", line 304, in main
    nb_filters=FLAGS.nb_filters)
  File "mnist_tutorial_tf_new_tsr.py", line 220, in mnist_tutorial
    args=train_params, rng=rng, var_list=model.get_params())
  File "/home/administrator/Downloads/cleverhans_new/cleverhans/cleverhans/train.py", line 264, in train
    evaluate()
  File "mnist_tutorial_tf_new_tsr.py", line 216, in evaluate
    do_eval(preds_adv, x_test, y_test, 'train_clean_train_adv_eval',True)
  File "mnist_tutorial_tf_new_tsr.py", line 187, in do_eval
    acc = model_eval(sess, x, y, preds, x_set, y_set, args=eval_params)
  File "/home/administrator/Downloads/cleverhans_new/cleverhans/cleverhans/utils_tf.py", line 260, in model_eval
    cur_corr_preds = correct_preds.eval(feed_dict=feed_dict)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 656, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5016, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x <= y did not hold element-wise:x (Placeholder:0) = ] [[[[70][90][90]]]...] [y (Cast_3/x:0) = ] [1]
	 [[Node: assert_less_equal_1/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_FLOAT, DT_STRING, DT_FLOAT], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](assert_less_equal_1/Assert/AssertGuard/Assert/Switch, assert_less_equal_1/Assert/AssertGuard/Assert/data_0, assert_less_equal_1/Assert/AssertGuard/Assert/data_1, assert_less_equal_1/Assert/AssertGuard/Assert/Switch_1, assert_less_equal_1/Assert/AssertGuard/Assert/data_3, assert_less_equal_1/Assert/AssertGuard/Assert/Switch_2/_95)]]

Caused by op 'assert_less_equal_1/Assert/AssertGuard/Assert', defined at:
  File "mnist_tutorial_tf_new_tsr.py", line 321, in <module>
    tf.app.run()
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "mnist_tutorial_tf_new_tsr.py", line 304, in main
    nb_filters=FLAGS.nb_filters)
  File "mnist_tutorial_tf_new_tsr.py", line 207, in mnist_tutorial
    adv_x = fgsm.generate(x, **fgsm_params)
  File "/home/administrator/Downloads/cleverhans_new/cleverhans/cleverhans/attacks/fast_gradient_method.py", line 61, in generate
    sanity_checks=self.sanity_checks)
  File "/home/administrator/Downloads/cleverhans_new/cleverhans/cleverhans/attacks/fast_gradient_method.py", line 159, in fgm
    asserts.append(utils_tf.assert_less_equal(x, tf.cast(clip_max, x.dtype)))
  File "/home/administrator/Downloads/cleverhans_new/cleverhans/cleverhans/utils_tf.py", line 627, in assert_less_equal
    return tf.assert_less_equal(*args, **kwargs)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/ops/check_ops.py", line 627, in assert_less_equal
    return control_flow_ops.Assert(condition, data, summarize=summarize)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 180, in Assert
    guarded_assert = cond(condition, no_op, true_assert, name="AssertGuard")
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2056, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1897, in BuildCondBranch
    original_result = fn()
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 178, in true_assert
    condition, data, summarize, name="Assert")
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 51, in _assert
    name=name)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/home/administrator/.virtualenvs/p35_tf17/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): assertion failed: [] [Condition x <= y did not hold element-wise:x (Placeholder:0) = ] [[[[70][90][90]]]...] [y (Cast_3/x:0) = ] [1]
	 [[Node: assert_less_equal_1/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_FLOAT, DT_STRING, DT_FLOAT], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](assert_less_equal_1/Assert/AssertGuard/Assert/Switch, assert_less_equal_1/Assert/AssertGuard/Assert/data_0, assert_less_equal_1/Assert/AssertGuard/Assert/data_1, assert_less_equal_1/Assert/AssertGuard/Assert/Switch_1, assert_less_equal_1/Assert/AssertGuard/Assert/data_3, assert_less_equal_1/Assert/AssertGuard/Assert/Switch_2/_95)]]

**System configuration**
 - OS : Ubuntu 16.04
 - Python version - 3.5
 - TensorFlow version- 1.7

**Comment by npapernot** [comment]
Did you ensure that the original unperturbed inputs, which you pass to the attack, satisfy all sanity checks defined here? (see all asserts.append() calls) https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks/fast_gradient_method.py#L166

**Comment by rohit789123** [comment]
@npapernot , thanks for the revert. yes, it is the sanity check which is failing. When i changed the flag ie set it to sanity_check=False , then the code is running fine. In the file 

https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks/fast_gradient_method.py

If i set "sanity_check=False", then too the adversarial examples get generated , so therefore i think that by changing sanity_check flag proper functioning of cleverhans doesn't get hindered. 

Please let me know if this is the case.

Thanks

**Comment by npapernot** [comment]
If the sanity checks are failing you might want to take a look at your inputs as they are probably not in the right domain to start with (their feature values do not satisfy the asserts performed when sanity_checks is set to True). This is something you would most likely want to fix rather than disable the sanity checks
