### ISSUE TITLE
tf.gradients(loss, x) returns None. Is CleverHans asking me to implement the gradient for a newly defined operation?

### ISSUE THREAD

**Issue by giuscri** [tensorflow/cleverhans#432]
I'm using `tf.py_func` to wrap a Python function and build a new operation. That is wrapped by a Keras layer that's the first one of a Keras `Sequential` model - it should perform a filtering task.

I've reproduced the problem on a script that should be easier to follow.

```python
     1  import tensorflow as tf
     2  from keras.models import Sequential
     3  from keras.layers import Dense, Activation
     4  from keras.engine.topology import Layer
     5  from cleverhans.utils_keras import KerasModelWrapper
     6  from cleverhans.attacks import FastGradientMethod
     7
     8  class MyLayer(Layer):
     9      def __init__(self, **kwargs):
    10          super(MyLayer, self).__init__(**kwargs)
    11
    12      def build(self, input_shape):
    13          super(MyLayer, self).build(input_shape)
    14
    15      def call(self, X):
    16          def __function(X): return np.sinh(X)
    17          return tf.reshape(tf.py_func(__function, [X], tf.float32), shape=(-1, *X.shape[1:]))
    18          # tf.reshape() is needed to enforce shape of output
    19
    20  kerasmodel = Sequential([
    21      # Dense(10, batch_input_shape=(None, 4)),
    22      # Activation('softmax'),
    23      MyLayer(batch_input_shape=(None, 4)),
    24      Activation('softmax'),
    25  ])
    26  kerasmodel.compile(optimizer='adagrad', loss='mse', metrics=['accuracy']) # randomly chosen params
    27
    28  cleverhansmodel = KerasModelWrapper(kerasmodel)
    29  attack = FastGradientMethod(cleverhansmodel)
    30
    31  Xsym = tf.placeholder(tf.float32, shape=(None, 4))
    32  attack.generate(Xsym)
```
If I run the above script,
```
$ python example.py
Using TensorFlow backend.
WARNING:tensorflow:From /home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/src/cleverhans/cleverhans/attacks.py:216: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/src/cleverhans/cleverhans/attacks_tf.py:62: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/src/cleverhans/cleverhans/utils_tf.py:37: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

Traceback (most recent call last):
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 420, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 420, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 32, in <module>
    attack.generate(Xsym)
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/src/cleverhans/cleverhans/attacks.py", line 294, in generate
    targeted=(self.y_target is not None))
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/src/cleverhans/cleverhans/attacks_tf.py", line 74, in fgm
    normalized_grad = tf.sign(grad)
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 453, in sign
    return gen_math_ops.sign(x, name=name)
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6877, in sign
    "Sign", x=x, name=name)
  File "/home/g/.local/share/virtualenvs/cleverhansexample-iTqMYa-7/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'x' to a tensor and failed. Error: None values not supported
```
What's triggering the error is https://github.com/tensorflow/cleverhans/blob/29e7e3b5ca1ca8fb1481c17d0875df2a323e3ae0/cleverhans/attacks_tf.py#L70-L74 It seems like CleverHans requires me to compute the gradient for the newly defined operation. But in the original case I don't know how to compute the gradient. The original function wrapped by _tf.py_func_ is rather complex. Also I'm planning to wrap a variety of functions and understanding what the gradient is for all of them is a pain.

Note that decommenting lines 21, 22 of the above script makes CleverHans quite again.

**Comment by gokul-uf** [comment]
In  `__function`, why not use `tf.sinh` instead of `np.sinh`?

**Comment by giuscri** [comment]
that's unrelated to the issue.

By the way, the point of using `tf.py_func` is building new operators without using TensorFlow operators but a Python function.

**Comment by goodfeli** [comment]
If you use a gradient-based attack, the gradient does need to be defined. That's going to be true regardless of software framework.
