### ISSUE TITLE
NotImplementedError: `fprop` not implemented.

### ISSUE THREAD

**Issue by pwna5aurus** [tensorflow/cleverhans#491]
Within the Model class, it keeps attempted to call self.fprop (which looks to be intentionally broken) instead of the CallableModelWrapper.fprop().  Is there a fix coming for this?  Or can I roll back to a previous version?

> 2018-08-08 15:43:41.672952: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "blackbox.py", line 199, in <module>
    main()
  File "blackbox.py", line 196, in main
    pwn(image,label)
  File "blackbox.py", line 144, in pwn
    batch_size=10)
  File "/usr/local/lib/python3.6/dist-packages/cleverhans/attacks.py", line 151, in generate_np
    self.construct_graph(fixed, feedable, x_val, hash_key)
  File "/usr/local/lib/python3.6/dist-packages/cleverhans/attacks.py", line 125, in construct_graph
    x_adv = self.generate(x, **new_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cleverhans/attacks.py", line 1117, in generate
    labels, nb_classes = self.get_or_guess_labels(x, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cleverhans/attacks.py", line 218, in get_or_guess_labels
    preds = self.model.get_probs(x)
  File "/usr/local/lib/python3.6/dist-packages/cleverhans/model.py", line 48, in get_probs
    d = self.fprop(x, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cleverhans/model.py", line 104, in fprop
    return {self.output_layer: self.callable_fn(x, **kwargs)}
  File "/usr/local/lib/python3.6/dist-packages/cleverhans/model.py", line 32, in __call__
    return self.get_probs(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cleverhans/model.py", line 48, in get_probs
    d = self.fprop(x, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cleverhans/model.py", line 63, in fprop
    raise NotImplementedError('`fprop` not implemented.')
NotImplementedError: `fprop` not implemented.

**Comment by pwna5aurus** [comment]
Latest as of 2 weeks ago.

**Comment by npapernot** [comment]
Could you share a bit more context with a code snippet for instance?

**Comment by goodfeli** [comment]
Closed for lack of discussion. Happy to address the issue if you can report more detail on how to reproduce it.
