### ISSUE TITLE
error in utils_mnist.py

### ISSUE THREAD

**Issue by hosna** [tensorflow/cleverhans#524]
I am trying to run your mnist_blackbox_keras.py
but I am getting:

Traceback (most recent call last):
  File "examples/mnist_blackbox_keras.py", line 305, in <module>
    tf.app.run()
  File "/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "examples/mnist_blackbox_keras.py", line 285, in main
    lmbda=FLAGS.lmbda, aug_batch_size=FLAGS.data_aug_batch_size)
  File "examples/mnist_blackbox_keras.py", line 220, in mnist_blackbox
    test_end=test_end)
  File "cleverhans/cleverhans/utils_mnist.py", line 95, in data_mnist
    'train-images-idx3-ubyte.gz', datadir=datadir) / 255.
  File "cleverhans/cleverhans/utils_mnist.py", line 68, in download_and_parse_mnist_file
    data = array.array(data_type, file_descriptor.read())
TypeError: must be char, not unicode

could you help me with it. 
Thanks.

**Comment by npapernot** [comment]
Are you using python 2 or 3?

**Comment by hosna** [comment]
Hi,
could you let me know if you find the reason?

**Comment by npapernot** [comment]
What happens when you replace [L48](https://github.com/tensorflow/cleverhans/blob/master/cleverhans/utils_mnist.py#L48) of `utils_mnist.py` with the following?

```
with open_fn(file_name, 'r') as file_descriptor:
```

**Comment by ftarlao** [comment]
I have a similar problem with the mnist + keras tutorial (mnist_tutorial_keras_tf.py
), I have tried changing L48 but I obtain the same error:
```
Using TensorFlow backend.
2018-09-18 15:33:49.761729: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-18 15:33:49.762655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
totalMemory: 1.96GiB freeMemory: 1.92GiB
2018-09-18 15:33:49.762684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-09-18 15:33:50.757986: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-18 15:33:50.758023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-09-18 15:33:50.758034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-09-18 15:33:50.773126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1689 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "/home/fab/python-workspace/ArticleFishingCNN/postcrisis/cleverhans-tutorial.py", line 237, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/fab/python-workspace/ArticleFishingCNN/postcrisis/cleverhans-tutorial.py", line 223, in main
    load_model=FLAGS.load_model)
  File "/home/fab/python-workspace/ArticleFishingCNN/postcrisis/cleverhans-tutorial.py", line 86, in mnist_tutorial
    test_end=test_end)
  File "/usr/local/lib/python2.7/dist-packages/cleverhans/utils_mnist.py", line 94, in data_mnist
    'train-images-idx3-ubyte.gz', datadir=datadir) / 255.
  File "/usr/local/lib/python2.7/dist-packages/cleverhans/utils_mnist.py", line 68, in download_and_parse_mnist_file
    data = array.array(data_type, file_descriptor.read())
TypeError: must be char, not unicode
```

**Comment by ftarlao** [comment]
I sent a Pull request with a working Python2 fix:
https://github.com/tensorflow/cleverhans/pull/569

**Comment by hosna** [comment]
it did not solve the problem for me I am yet getting the error as 
utils_mnist.py", line 68, in download_and_parse_mnist_file
    data = array.array(data_type, file_descriptor.read())
TypeError: must be char, not unicode

**Comment by ftarlao** [comment]
My pull request is made of 4 commits, you need the merge of all 4 commits. I have checked it with Python 2.7 and 3.4, and the TRAVIS integration of the repository confirms the fix for Python 2.7/3.5.

**Comment by hosna** [comment]
I applied all the commits 
utils_mnist.py", line 94, in data_mnist
    'train-images-idx3-ubyte.gz', datadir=datadir) / 255.
 src/cleverhans/cleverhans/utils_mnist.py", line 68, in download_and_parse_mnist_file
    data = array.array(data_type, file_descriptor.read())
TypeError: must be char, not unicode

**Comment by ftarlao** [comment]
It is only to be sure&safe that you updated the file correctly, please copy/paste (I think) L65-L70, the lines just after `the  hex_to_data_type = {..}` part.

**Comment by hosna** [comment]
I build the lib again. I think only copy paste wont help, one need to re install cleverhans with pip install ...

**Comment by hosna** [comment]
copy paste was not enough. one need to do pip install cleve.... again I think. 
though now I am getting new errors /~_~\

**Comment by ftarlao** [comment]
you are welcome :-)
