### ISSUE TITLE
error in ex_cifar10_tf.py

### ISSUE THREAD

**Issue by pcham** [tensorflow/cleverhans#541]
The parameters passed for the train function  in line 116 does not match the method signature. 
train(sess, x, y, predictions, X_train, Y_train,
          evaluate=evaluate, args=train_params)

def train(sess, loss, x, y, X_train, Y_train, save=False,
          init_all=True, evaluate=None, feed=None, args=None,
          rng=None, var_list=None, fprop_args=None, optimizer=None):

Training fails with message:

Traceback (most recent call last):
  File "ex_cifar10_tf.py", line 194, in <module>
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "ex_cifar10_tf.py", line 116, in main
    evaluate=evaluate, args=train_params)
  File "~/Project/ProjectCodeAdversarialExamples/cleverhans/utils_tf.py", line 118, in train
    loss_value = loss.fprop(x, y, **fprop_args)
AttributeError: 'Tensor' object has no attribute 'fprop'

**Comment by npapernot** [comment]
This example is outdated because we don't maintain the examples folder. I recommend you take a look at the most recent `cleverhans_tutorials/mnist_tutorial_tf.py`, which you can adapt to run on CIFAR
