### ISSUE TITLE
ValueError: Tried to convert 'depth' to a tensor and failed. Error: None values not supported.

### ISSUE THREAD

**Issue by yyy32** [tensorflow/cleverhans#917]
ValueError: Tried to convert 'depth' to a tensor and failed. Error: None values not supported.

When I run SPSA to craft adversarial examples in my pytorch model:
   
     ` sess = tf.Session()
        tf_model_fn = convert_pytorch_model_to_tf(model)
        cleverhans_model = CallableModelWrapper(tf_model_fn, output_layer='logits')
        x_input = tf.placeholder(tf.float32, shape=(1,32,32,3))
        y_label = tf.placeholder(tf.int32, shape=(1,))
        attack = SPSA(cleverhans_model,sess=sess)
        x_adv = attack.generate(x_input,y=y_label,epsilon=eps,nb_iter=100,
                        clip_min=clip_min,clip_max=clip_max,spsa_iters=1,spsa_samples=32)

        for k in range(len(data)):
            x = np.expand_dims(data[k].permute(1,2,0).cpu().numpy(),axis=0)
            y = np.expand_dims(target[k].item(),axis=0)  
            adv_data = sess.run(x_adv,feed_dict={x_input:x,y_label:y})
            if adv_data is None:
                input_adv.append(np.asarray(data[k]))
            else:
                input_adv.append(adv_data)`
ubuntu python3.5 tensorflow1.2 pytorch0.4.0

   

`2018-12-04 17:04:41.613538: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py:2029: UserWarning: `epsilon` is deprecated. Switch to `eps`. `epsilon` may be removed on or after 2019-04-15.
  warnings.warn("`epsilon` is deprecated. Switch to `eps`. `epsilon` may "
Traceback (most recent call last):
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 430, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 430, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "newidea/spsatest.py", line 185, in <module>
    test(model,test_model,test_loader)
  File "newidea/spsatest.py", line 108, in test
    clip_min=clip_min,clip_max=clip_max,spsa_iters=1,spsa_samples=32)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2095, in generate
    clip_max=clip_max
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2679, in projected_optimization
    back_prop=False)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2645, in loop_body
    wrapped_loss_fn, [perturbation], optim_state)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1523, in minimize
    grads = self._compute_gradients(loss_fn, x, optim_state)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1680, in _compute_gradients
    parallel_iterations=1)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1663, in body
    loss_fn(x + delta_x),
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2642, in wrapped_loss_fn
    return loss_fn(input_image + x, label)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2082, in loss_fn
    logits, label, nb_classes=self.model.nb_classes)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1710, in margin_logit_loss
    logit_mask = tf.one_hot(label, depth=nb_classes, axis=-1)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2445, in one_hot
    name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4724, in one_hot
    off_value=off_value, axis=axis, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'depth' to a tensor and failed. Error: None values not supported.`

**Comment by david-berthelot** [comment]
I suspect you didn't pass an argument to your model when instantiating it. Like it's expecting some depth you didn't provide like: 
```
model = functools.partial(model, depth=32)  # Or whatever depth you want to use.
```

Do you have a running example I can look at?

**Comment by yyy32** [comment]
Thanks for your reply. There is my code.
```
from __future__ import print_function
import argparse
import torch
import torch.optim as optim
import numpy as np
from torch import nn
from torchvision import datasets, transforms
from torch.autograd import Variable
import tensorflow as tf
from tensorflow.python.platform import flags
from mnist import LeNet5
from cleverhans.attacks import CarliniWagnerL2,SPSA
from cleverhans.model import CallableModelWrapper
from cleverhans.utils import AccuracyReport
from cleverhans.utils_pytorch import convert_pytorch_model_to_tf
dataset_options = ['cifar10', 'cifar100', 'svhn','mnist']
parser = argparse.ArgumentParser(description=' test')
parser.add_argument('--dataset', '-d', default='svhn',
                    choices=dataset_options)
parser.add_argument('--batch-size', type=int, default=128, metavar='N',
                    help='input batch size for training (default: 64)')
parser.add_argument('--seed', type=int, default=1, metavar='S',
                    help='random seed (default: 1)')
parser.add_argument('--max-steps', type=int, default=500, metavar='maxstep',
                    help='max steps of CW attack (default: 400)')
device = torch.device("cuda")
args = parser.parse_args()
torch.manual_seed(args.seed)
if args.dataset == 'mnist':
    test_loader = torch.utils.data.DataLoader(
        datasets.MNIST('data/mnist', train=False, transform=transforms.Compose([
                           transforms.ToTensor(),
                           transforms.Normalize(mean = [0.5,0.5,0.5],std=[0.5,0.5,0.5]),
                       ])),
        batch_size=args.batch_size, shuffle=True, num_workers=2,pin_memory=True)
elif args.dataset == 'cifar10':
    num_classes = 10
    test_loader = torch.utils.data.DataLoader(
        datasets.CIFAR10(root='data/',train=False,download=False,
                         transform=transforms.Compose([ 
                             transforms.RandomCrop(32, padding=4),  
                             transforms.Scale(32),  
                             transforms.RandomHorizontalFlip(),  
                             transforms.ToTensor(),  
                             transforms.Normalize(mean = [0.5,0.5,0.5],std=[0.5,0.5,0.5]),
                         ])),  
        batch_size=args.batch_size, shuffle=True, num_workers=2,pin_memory=True)
criterion = nn.CrossEntropyLoss()
def test(model, test_model, loader):
    # for t_model in test_model:
    test_model.eval()
    model.eval()    # Change model to 'eval' mode (BN uses moving mean/var).
    total = 0.
    correct = 0.
    ## create cleverhans-model
    tf_model_fn = convert_pytorch_model_to_tf(model)
    cleverhans_model = CallableModelWrapper(tf_model_fn, output_layer='logits')
    eps = 8./255
    clip_max=1.0
    clip_min=-1.0
for batch_idx, (data, target) in enumerate(test_loader):
        data, target = data.to(device), target.to(device)        
        if batch_idx > 0: break
        input_adv=[]
        sess = tf.Session()
        if args.dataset=='mnist':
            x_input = tf.placeholder(tf.float32, shape=(1,28,28,1))
        else:
            x_input = tf.placeholder(tf.float32, shape=(1,32,32,3))
        y_label = tf.placeholder(tf.int32, shape=(1,))
        attack = SPSA(cleverhans_model,sess=sess)
        x_adv = attack.generate(x_input,y=y_label,eps=eps,nb_iter=100,
                        clip_min=clip_min,clip_max=clip_max,spsa_iters=1,spsa_samples=32)
        for k in range(len(data)):
            x = np.expand_dims(data[k].permute(1,2,0).cpu().numpy(),axis=0)
            print(np.shape(x))
            y = np.expand_dims(target[k].item(),axis=0)  
            adv_data = sess.run(x_adv,feed_dict={x_input:x,y_label:y})
            if adv_data is None:
                input_adv.append(np.asarray(data[k]))
            else:
                input_adv.append(adv_data)
        input_adv = np.array(input_adv)
        data = torch.tensor(input_adv).pertmute(2,0,1).to(device)
        total += target.size(0)  # 
        output = test_model(data)
        pred = torch.max(output.detach(), 1)[1]
        correct += (pred == target.detach()).sum()

    return correct.item() / total

model = LeNet5()
model.to(device)
model.load_state_dict(torch.load('newidea/file/mnist/no.pt'))
test(model, model, loader)
```

```
Traceback (most recent call last):
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 430, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 430, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "newidea/spsatest.py", line 130, in <module>
    test(model, model, test_loader)
  File "newidea/spsatest.py", line 103, in test
    clip_min=clip_min,clip_max=clip_max,spsa_iters=1,spsa_samples=32)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2095, in generate
    clip_max=clip_max
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2679, in projected_optimization
    back_prop=False)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2645, in loop_body
    wrapped_loss_fn, [perturbation], optim_state)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1523, in minimize
    grads = self._compute_gradients(loss_fn, x, optim_state)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1680, in _compute_gradients
    parallel_iterations=1)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1663, in body
    loss_fn(x + delta_x),
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2642, in wrapped_loss_fn
    return loss_fn(input_image + x, label)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2082, in loss_fn
    logits, label, nb_classes=self.model.nb_classes)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1710, in margin_logit_loss
    logit_mask = tf.one_hot(label, depth=nb_classes, axis=-1)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2445, in one_hot
    name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4724, in one_hot
    off_value=off_value, axis=axis, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'depth' to a tensor and failed. Error: None values not supported.
```

**Comment by yyy32** [comment]
Thanks for the reply. I uploaded the code under this [repository](https://github.com/yyy32/spsa). The code for the model architecture is located in the mnist.py.

**Comment by david-berthelot** [comment]
I'm submitting an improvement to solve the problem you had. In the meantime, you can use this workaround:
```
cleverhans_model.nb_classes = 10
```

**Comment by yyy32** [comment]
Thanks for your reply. I add `cleverhans_model.nb_classes = 10`, but it still does not work.

```
 2018-12-13 15:54:12.451287: W tensorflow/core/framework/op_kernel.cc:1261] Unknown: RuntimeError: Given groups=1, weight[6, 1, 5, 5], so expected input[32, 28, 28, 1] to have 1 channels, but got 28 channels instead
Traceback (most recent call last):

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/utils_pytorch.py", line 59, in _fprop_fn
    torch_state['logits'] = model(torch_state['x'])

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/newidea/mnist.py", line 84, in forward
    x = self.features(x)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)

RuntimeError: Given groups=1, weight[6, 1, 5, 5], so expected input[32, 28, 28, 1] to have 1 channels, but got 28 channels instead


Traceback (most recent call last):
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: RuntimeError: Given groups=1, weight[6, 1, 5, 5], so expected input[32, 28, 28, 1] to have 1 channels, but got 28 channels instead
Traceback (most recent call last):

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/utils_pytorch.py", line 59, in _fprop_fn
    torch_state['logits'] = model(torch_state['x'])

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/newidea/mnist.py", line 84, in forward
    x = self.features(x)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)

RuntimeError: Given groups=1, weight[6, 1, 5, 5], so expected input[32, 28, 28, 1] to have 1 channels, but got 28 channels instead


	 [[{{node while/while/PyFunc}} = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], _gradient_op_type="PyFuncGrad-63031c8cd4e89c60328e359b5703f1", token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/while/add_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "newidea/spsatest.py", line 132, in <module>
    test(model, model, test_loader)
  File "newidea/spsatest.py", line 112, in test
    adv_data = sess.run(x_adv,feed_dict={x_input:x,y_label:y})
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: RuntimeError: Given groups=1, weight[6, 1, 5, 5], so expected input[32, 28, 28, 1] to have 1 channels, but got 28 channels instead
Traceback (most recent call last):

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/utils_pytorch.py", line 59, in _fprop_fn
    torch_state['logits'] = model(torch_state['x'])

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/newidea/mnist.py", line 84, in forward
    x = self.features(x)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)

RuntimeError: Given groups=1, weight[6, 1, 5, 5], so expected input[32, 28, 28, 1] to have 1 channels, but got 28 channels instead


	 [[node while/while/PyFunc (defined at /home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/utils_pytorch.py:35)  = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], _gradient_op_type="PyFuncGrad-63031c8cd4e89c60328e359b5703f1", token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/while/add_1)]]

Caused by op 'while/while/PyFunc', defined at:
  File "newidea/spsatest.py", line 132, in <module>
    test(model, model, test_loader)
  File "newidea/spsatest.py", line 104, in test
    clip_min=clip_min,clip_max=clip_max,spsa_iters=1,spsa_samples=32)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2095, in generate
    clip_max=clip_max
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2679, in projected_optimization
    back_prop=False)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2645, in loop_body
    wrapped_loss_fn, [perturbation], optim_state)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1523, in minimize
    grads = self._compute_gradients(loss_fn, x, optim_state)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1680, in _compute_gradients
    parallel_iterations=1)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks_tf.py", line 1663, in body
    loss_fn(x + delta_x),
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2642, in wrapped_loss_fn
    return loss_fn(input_image + x, label)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/attacks/__init__.py", line 2079, in loss_fn
    logits = self.model.get_logits(x)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/model.py", line 65, in get_logits
    outputs = self.fprop(x, **kwargs)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/model.py", line 226, in fprop
    output = self.callable_fn(x, **kwargs)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/utils_pytorch.py", line 84, in tf_model_fn
    grad_func=_tf_gradient_fn)[0]
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/utils_pytorch.py", line 35, in _py_func_with_gradient
    return tf.py_func(func, inp, Tout, stateful=stateful, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 457, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 281, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 129, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): RuntimeError: Given groups=1, weight[6, 1, 5, 5], so expected input[32, 28, 28, 1] to have 1 channels, but got 28 channels instead
Traceback (most recent call last):

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/utils_pytorch.py", line 59, in _fprop_fn
    torch_state['logits'] = model(torch_state['x'])

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/newidea/mnist.py", line 84, in forward
    x = self.features(x)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/yueyao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)

RuntimeError: Given groups=1, weight[6, 1, 5, 5], so expected input[32, 28, 28, 1] to have 1 channels, but got 28 channels instead


	 [[node while/while/PyFunc (defined at /home/yueyao/anaconda3/lib/python3.6/site-packages/cleverhans/utils_pytorch.py:35)  = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], _gradient_op_type="PyFuncGrad-63031c8cd4e89c60328e359b5703f1", token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/while/add_1)]]

```

**Comment by david-berthelot** [comment]
Yes but that seems like a problem with your model being NCHW while the input is NHWC. So I don't think we need to change anything in CleverHans for this.

**Comment by yyy32** [comment]
Thanks a lot for your help. The problem is solved.

**Comment by Luobuyao** [comment]
i have the same problem,how can you solve it?

**Comment by npapernot** [comment]
Based on the thread above, you have to upgrade CleverHans to the latest version and make sure that your input is in the same format than the model (NCHW or NHWC)
